---
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Copy nginx starting page
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - {"src": "nginx/index.html", "dest": "/var/www/html/index.nginx-debian.html"}
    - {"src": "nginx/exporter.conf", "dest": "/etc/nginx/conf.d/exporter.conf"}

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Verify nginx is serving web requests
  uri:
    url: http://localhost/
    status_code: 200
