- name: Install nginx
  package:
    name: nginx
    state: present

- name: Copy nginx starting page
  copy:
    src: "nginx/index.html"
    dest: "/var/www/html/index.nginx-debian.html"
    owner: root
    group: root
    mode: 0644

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Verify nginx is serving web requests
  uri:
    url: http://localhost/
    status_code: 200